export enum ReferralMessage {
	REFERRAL_FAIL_LIMIT = 'REFERRAL_FAIL_LIMIT',
	CLAIM_NFT_FAIL_HAS_NFT = 'CLAIM_NFT_FAIL_HAS_NFT'
}
export enum AmbassadorStatus {
	CLAIM_AVAILABLE = 'CLAIM_AVAILABLE',
	NOT_ELIGIBLE = 'NOT_ELIGIBLE',
	HAS_AMBASSADOR_NFT = 'HAS_AMBASSADOR_NFT'
}
