export enum ErrorCode {
	NOT_FOUND = 'NOT_FOUND',
	UNAUTHENTICATED = 'UNAUTHENTICATED',
	FORBIDDEN = 'FORBIDDEN',
	VALIDATION_ERROR = 'VALIDATION_ERROR'
}

export const ERROR_EMAIL_ALREADY_REGISTERED = 'Email address already registered';
